runtime: python39

entrypoint: gunicorn -b :$PORT backend.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: backend.settings
  SECRET_KEY: "django-insecure-sr&dj5@(!i_!ig3=ee3mp&ymw0sf*p+9q&u4x@$7u1xpycssei"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
